language: python
python:
- 3.4


#installtion
  #before install
  #install
install:
  - pip install -r requirements.txt
  
addons:
  sonarcloud:
    organization: "varunudemy5_TravisCI_T"

git:
  depth: false

#script
  #before_script
  #script
  
script:
   - python3 test_fruits.py
   - mkdir ShortStory
   - cd ShortStory
   - touch KKK
   - echo 5

#after script
  #after sucess
  #after failure

#deploy
  #before deploy
  #deploy
  #after deploy

#safelist
branches:
  only:
  - master
  - /[upt][a-q]*[t]\b//
  
#blocklist
branches:
  except:
  - opt
#comments
#comment
